import React from "react";
import { shallow, mount } from "enzyme";
import toJSON from "enzyme-to-json";
import { ErrorBoundary } from "./ErrorBoundary";

const ComponentWithError = () => {
    throw new Error("NEW ERROR");
};

describe("ErrorBoundary", () => {
    it("should match the snapshot", () => {
        const component = shallow(<ErrorBoundary>Test</ErrorBoundary>);
        expect(toJSON(component)).toMatchSnapshot();
    });

    it("renders null when error generated by child", () => {
        const consoleError = console.error;
        console.error = () => {};

        const wrapper = mount(
            <ErrorBoundary>
                <ComponentWithError />
            </ErrorBoundary>,
        );

        console.error = consoleError;
        expect(wrapper.html()).toBe(null);
    });
});
